version: '3.3'

services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - './sql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: website_review_user
      POSTGRES_DB: website_review

volumes:
  postgres:

